apiVersion: v1.0
pipelines:
  - name: java_native_cli_graalvm_picocli
    steps:
      # see https://www.jfrog.com/confluence/display/JFROG/MvnBuild
      - name: mvn_install
        type: MvnBuild
        configuration:
          mvnCommand: -Dskip=true clean install # TODO: revert to -Dskip=false
          sourceLocation: .
          configFileLocation: jfrog
          configFileName: mvn-art-config
          forceXrayScan: false
          # failOnScan: true
          autoPublishBuildInfo: true

          integrations:
            - name: kirasoa_artifactory
          inputResources:
            - name: src_GitRepo
          outputResources:
            - name: mvn_BuildInfo
          runtime:
            type: image
            image:
              custom:
                name: kirasoa/pipelines-u18graalvm
                tag: "11"
        execution:
          onStart:
            - echo "[TM] onStart"
            - restore_cache_files m2_cache ${HOME}/.m2
            - java -version
            - mvn -version
          onSuccess:
            - echo "[TM] onSuccess"
            - add_cache_files ${HOME}/.m2 m2_cache
            # TODO: revert to target/checksum
            - jfrog rt u ${res_src_GitRepo_resourcePath}/jfrog/checksum generic-local/latest/ --build-name=${res_mvn_BuildInfo_buildName} --build-number=${res_mvn_BuildInfo_buildNumber}
          onFailure:
            - echo "[TM] onFailure"
          onComplete:
            - echo "[TM] onComplete"

      # - name: scan_mvn
      #   type: XrayScan
      #   configuration:
      #     failOnScan: true
      #     inputResources:
      #       - name: mvn_BuildInfo
      #         trigger: true
      #     # outputResources:
      #     #   - name: mvn_scan_BuildInfo

      - name: test_for_staging
        type: Bash
        configuration:
          inputSteps:
            - name: mvn_install
        execution:
          onExecute:
            - echo "executing integration test"

      - name: promote_to_staging
        type: PromoteBuild
        configuration:
          targetRepository: libs-staging-local
          includeDependencies: false
          status: STAGING
          comment: integration tests passed
          # copy: false
          inputResources:
            - name: mvn_BuildInfo
              trigger: true
          inputSteps:
            - name: test_for_staging
          outputResources:
            - name: mvn_staging_BuildInfo

      - name: test_for_release
        type: Bash
        configuration:
          inputSteps:
            - name: promote_to_staging
        execution:
          onExecute:
            - echo "executing UAT"

      - name: promote_to_release
        type: PromoteBuild
        configuration:
          targetRepository: libs-release-local
          includeDependencies: false
          status: RELEASE
          comment: UAT passed
          # copy: false
          inputResources:
            - name: mvn_staging_BuildInfo
              trigger: true
          inputSteps:
            - name: test_for_release
          outputResources:
            - name: mvn_release_BuildInfo            