apiVersion: v1.0
pipelines:
  - name: java_native_cli_graalvm_picocli
    steps:
      # see https://www.jfrog.com/confluence/display/JFROG/MvnBuild
      - name: mvn_pacakge_skip_image
        type: MvnBuild
        configuration:
          mvnCommand: -Dskip=false clean install
          sourceLocation: .
          configFileLocation: jfrog
          configFileName: mvn-art-config
          # forceXrayScan: false
          # failOnScan: true
          autoPublishBuildInfo: true

          integrations:
            - name: kirasoa_artifactory
          inputResources:
            - name: src_GitRepo
          outputResources:
            - name: mvn_pacakge_skip_image_BuildInfo
          runtime:
            type: image
            image:
              custom:
                name: kirasoa/pipelines-u18graalvm
                tag: "11"
        execution:
          onStart:
            - echo "[TM] onStart"
            - java -version
            - mvn -version
          onSuccess:
            - echo "[TM] onSuccess"
            - jfrog rt u ${res_sandbox_GitRepo_resourcePath}/target/checksum generic-local/latest/
          onFailure:
            - echo "[TM] onFailure"
          onComplete:
            - echo "[TM] onComplete"
