apiVersion: v1.0
pipelines:
  - name: java_native_cli_graalvm_picocli
    steps:
      # see https://www.jfrog.com/confluence/display/JFROG/MvnBuild
      - name: mvn_install
        type: MvnBuild
        configuration:
          mvnCommand: -Dskip=true clean install # TODO: revert to -Dskip=false
          sourceLocation: .
          configFileLocation: jfrog
          configFileName: mvn-art-config
          forceXrayScan: false
          # failOnScan: true
          autoPublishBuildInfo: true

          integrations:
            - name: kirasoa_artifactory
          inputResources:
            - name: src_GitRepo
          outputResources:
            - name: mvn_BuildInfo
          runtime:
            type: image
            image:
              custom:
                name: kirasoa/pipelines-u18graalvm
                tag: "11"
        execution:
          onStart:
            - echo "[TM] onStart"
            - restore_cache_files m2_cache ${HOME}/.m2
            - java -version
            - mvn -version
          onSuccess:
            - echo "[TM] onSuccess"
            - add_cache_files ${HOME}/.m2 m2_cache
            - jfrog rt u ${res_src_GitRepo_resourcePath}/target/checksum generic-local/latest/
          onFailure:
            - echo "[TM] onFailure"
          onComplete:
            - echo "[TM] onComplete"

      # - name: scan_mvn
      #   type: XrayScan
      #   configuration:
      #     failOnScan: true
      #     inputResources:
      #       - name: mvn_BuildInfo
      #         trigger: true
      #     # outputResources:
      #     #   - name: mvn_scan_BuildInfo

      - name: promote
        type: PromoteBuild
        configuration:
          targetRepository: libs-release-local
          includeDependencies: false
          status: RELEASE
          comment: ready to release
          # copy: false
          inputResources:
            - name: mvn_BuildInfo
              trigger: true
          inputSteps:
            - name: mvn_install
          outputResources:
            - name: mvn_promoted_BuildInfo