apiVersion: v1.0
pipelines:
  - name: java_native_cli_graalvm_picocli
    steps:
      # see https://www.jfrog.com/confluence/display/JFROG/MvnBuild
      - name: mvn_install
        type: MvnBuild
        configuration:
          mvnCommand: -Dskip=true clean install # TODO: revert to -Dskip=false
          sourceLocation: .
          configFileLocation: jfrog
          configFileName: mvn-art-config
          forceXrayScan: true
          # failOnScan: true
          autoPublishBuildInfo: true

          integrations:
            - name: kirasoa_artifactory
          inputResources:
            - name: src_GitRepo
          outputResources:
            - name: java_native_cli_graalvm_picocli_mvn
          runtime:
            type: image
            image:
              custom:
                name: kirasoa/pipelines-u18graalvm
                tag: "11"
        execution:
          onStart:
            - echo "[TM] onStart"
            - java -version
            - mvn -version
            - restore_cache_files m2_cache ${HOME}/.m2
          onSuccess:
            - echo "[TM] onSuccess"
            - jfrog rt u ${res_src_GitRepo_resourcePath}/target/checksum generic-local/latest/
            - add_cache_files ${HOME}/.m2 m2_cache
          onFailure:
            - echo "[TM] onFailure"
          onComplete:
            - echo "[TM] onComplete"

      - name: scan_mvn_pacakge
        type: XrayScan
        configuration:
          failOnScan: true
          inputResources:
            - name: java_native_cli_graalvm_picocli_mvn
              trigger: true
          # outputResources:
          #   - name: java_native_cli_graalvm_picocli_mvn_scan
